### PR TITLE
rename routes to avoid override others devise strategies routes

### PR DESCRIPTION
**Pull request by JotaSe**
This changes avoid to create custom scopes for differents authentication strategies [Supporting multiple authentication strategies](https://github.com/apokalipto/devise_saml_authenticatable/wiki/Supporting-multiple-authentication-strategies) the routes

**extra:** I changed code styles

### CODE REVIEW

**Comment by adamstegman** [comment]
Thank you for the contribution! Do you think this is appropriate by default? I'm a little concerned about overriding the default devise helpers like `new_user_session` for apps that don't use multiple strategies.

**Comment by JotaSe** [comment]
It will work anyway, the most common use is let devise use the strategy, we won't call the strategy action directly, the controller does (Devise::SamlSessionsController)

**Comment by adamstegman** [comment]
Yes and no—you still have to make a logout link that goes to `destroy_user_session`, which means you need to know that it should be `destroy_user_saml_session`. Is there a way you could add this that allows either?

**Comment by shaicoleman** [comment]
This should be an optional setting, and keep the existing routes by default so existing apps don't break

**Comment by adamstegman** [comment]
Check out #133 for an opt-in solution to this issue!

**Pull request closed without merging**
