### PR TITLE
Add saml_auth_value_validator to have custom validation

### PR DESCRIPTION
**Pull request by deepinsand**
Closes apokalipto/devise_saml_authenticatable#66

### CODE REVIEW

**Comment by adamstegman** [comment]
Seems like a good idea! 👍 What kinds of validation do you foresee here? It might be helpful to pass the resource in as well.

Also looks like after merging #68 there's a merge conflict here.

**Comment by deepinsand** [comment]
Thanks for the quick reply, and apologies for the conflict!  The validation is meant to address the issue brought up in http://www.economyofmechanism.com/office365-authbypass.html

This issue occurs when an IDP goes rogue and sends back fake assertions. Even though the signature is correct, the assertions are all lies.  The vulnerability was closed in Office365, but I'm paranoid it might happen in any given server.

I had a second use case to check against nulls as well.  I had an incorrect attribute-map.yml, so it was retuning a null key.  This effectively gave access to random null-email users.

**Comment by adamstegman** [comment]
What do you think about passing the resource in? I could see that being useful to validate relay state or validating other attributes.

**Comment by deepinsand** [comment]
That makes a lot of sense!  I moved it to be a "saml_resource_validator".  I stopped sending the auth_value since it seemed redundant now.

I worry people might confuse this with ActiveRecord validation (difference is this is called on read), would love feedback there.

**Comment by adamstegman** [comment]
Phew, sorry for the delayed response, I've been swamped. This is a great idea, thank you for putting it together!

**Pull request merged**
