### PR TITLE
Store IDP session index in session to allow multiple sessions per user

### LINKED ISSUE #253: Allow multiple sessions per user
The SAML session index is required to perform an IDP-initiated logout and is used as authenticatable salt. Currently, this session index is stored directly on the user model. 

When the user logs in on a second device (or second browser, incognito window, ...), the session index of the primary device is overridden. This approach has the following problems:

- The primary device cannot be logged out through the IDP anymore.
- Because the authenticatable salt does not match the value stored in the session, Devise cannot fetch the user from the session anymore, causing 401s on the primary device for any subsequent requests. So this basically terminates the session on the primary device.

This behavior was already described in https://github.com/apokalipto/devise_saml_authenticatable/issues/151#issuecomment-540759920 and probably in other issues, but I have not found a dedicated issue just for this.

In our specific application, users could even end up in automatic login loops, when they log into a secondary devise. The JS frontend has a polling request that would get the 401 as described above (for the primary devise) and then redirect to the SAML login page. Because the IDP SAML session is still active, this directly redirects back to the application SessionController create, where a new session index is persisted in the user model. Now the secondary device gets the 401 and redirects to the SAML login, persisting another session index, and so on.

Our users switch regularly between workstations and/or mobile devices, so multiple active sessions per user is a must.

We currently solved the problem by patching this gem, removing the session index column on the user model, removing the usage of the session index as authenticatable salt and storing the session index in the Rack session only to be used for IDP logout. 

I am not that deep into Devise to decide how important it is to really use an authenticatable salt. If you think it could be left out as well, I would be happy to extract our patches as a pull request, so that the session index would only be stored in the session but not in the user model.

What do you think? Did you come up with other ways to tackle this issue?

### PR DESCRIPTION
**Pull request by codez**
fixes #253

### CODE REVIEW

**Comment by adamstegman** [comment]
@codez if you update from master, I've fixed these test failures. There's a few that do apply to this PR after that:

```
Failures:

  1) Devise::SamlSessionsController#idp_sign_out when receiving an IdP logout request direct the resource to reset the session key
     Failure/Error: Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
     
     Devise::MissingWarden:
       Devise could not find the `Warden::Proxy` instance on your request environment.
       Make sure that your application is loading Devise and Warden as expected and that the `Warden::Manager` middleware is present in your middleware stack.
       If you are seeing this on one of your tests, ensure that your tests are either executing the Rails middleware stack or that your tests are using the `Devise::Test::ControllerHelpers` module to inject the `request.env['warden']` object for you.
     # ./app/controllers/devise/saml_sessions_controller.rb:26:in `idp_sign_out'
     # ./spec/controllers/devise/saml_sessions_controller_spec.rb:359:in `block (4 levels) in <top (required)>'
     # ./spec/controllers/devise/saml_sessions_controller_spec.rb:376:in `block (4 levels) in <top (required)>'

  2) Devise::SamlSessionsController#idp_sign_out when receiving an IdP logout request with a specified idp accepts a LogoutResponse for the associated slo_target_url and redirects to sign_in
     Failure/Error: Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
     
     Devise::MissingWarden:
       Devise could not find the `Warden::Proxy` instance on your request environment.
       Make sure that your application is loading Devise and Warden as expected and that the `Warden::Manager` middleware is present in your middleware stack.
       If you are seeing this on one of your tests, ensure that your tests are either executing the Rails middleware stack or that your tests are using the `Devise::Test::ControllerHelpers` module to inject the `request.env['warden']` object for you.
     # ./app/controllers/devise/saml_sessions_controller.rb:26:in `idp_sign_out'
     # ./spec/controllers/devise/saml_sessions_controller_spec.rb:359:in `block (4 levels) in <top (required)>'
     # ./spec/controllers/devise/saml_sessions_controller_spec.rb:388:in `block (5 levels) in <top (required)>'

  3) Devise::SamlSessionsController#idp_sign_out when receiving an IdP logout request with a relay_state lambda defined includes the RelayState param in the request to the IdP
     Failure/Error: Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
     
     Devise::MissingWarden:
       Devise could not find the `Warden::Proxy` instance on your request environment.
       Make sure that your application is loading Devise and Warden as expected and that the `Warden::Manager` middleware is present in your middleware stack.
       If you are seeing this on one of your tests, ensure that your tests are either executing the Rails middleware stack or that your tests are using the `Devise::Test::ControllerHelpers` module to inject the `request.env['warden']` object for you.
     # ./app/controllers/devise/saml_sessions_controller.rb:26:in `idp_sign_out'
     # ./spec/controllers/devise/saml_sessions_controller_spec.rb:359:in `block (4 levels) in <top (required)>'
     # ./spec/controllers/devise/saml_sessions_controller_spec.rb:401:in `block (5 levels) in <top (required)>'
```

**Comment by codez** [comment]
I pushed a change the should fix those specs. Can you please re-start the action workflow?

**Comment by adamstegman** [comment]
I think we might be missing a test case for `saml_session_index_key` being set to `nil`, like in the README.

This also seems like a major version bump, since it enables IdP sign out by default, and changes its behavior pretty significantly. I'll take care of the version after merging this.

**Comment by codez** [comment]
I added one in `strategy_spec.rb`, another in `saml_sessions_controller_spec.rb` already exists.

I agree that this will be a major version bump.

**Pull request merged**
